##############
### Start ####
##############

# Dependencies
markdown:         kramdown

# Permalinks
permalink:        none

# Setup
title:            "galeo's blog"
tagline:          In the morning after, you begin to see the light.
url:              'https://blog.galeo.me'
paginate:         7

baseurl:          /
author:
  name:           Yuwei Tian
  url:            https://github.com/galeo
  email:          ibluefocus@NOSPAM.gmail.com

# Content
excerpt_separator: "</p>"
timezone:         UTC
future:           false

# Related pages
related:
  excluded_tags:  ['emacs']
  max_number:     3

# Comment service
comment_service:  'utterances'

pages_list:
  Blog: ['/index.html']
  Archive: ['/archive.html']
  Tags: ['/tags.html']
  About: ['/about.html']
  Home ⤶: ['https://blog.galeo.me/']

plugins:
  - jekyll-sitemap
  - jekyll-paginate
